### ISSUE TITLE
Reference to the KUBERNETES NAMESPACE is hard coded

### ISSUE THREAD

**Issue by cmoulliard** [cescoffier/vertx-configuration-service#3]
As the pod containing the code of Vert.X could be deployed within a different kube namespace, we should find a way to get the KUBERNETES_NAMESPACE value in order to avoid to hard code the info here : https://github.com/cescoffier/vertx-configuration-service/blob/master/vertx-configuration-kubernetes-configmap/src/main/java/examples/Examples.java#L19

That means that if we don't pass this mandatory value, we will try to load it using an env var.

**Comment by cescoffier** [comment]
Fix by #5
