### ISSUE TITLE
Allow to download the artifacts (releases/snapshots)

### ISSUE THREAD

**Issue by cazacugmihai** [cescoffier/vertx-configuration-service#6]
Please deploy the artifacts (releases/snapshots) somewhere (e.g.: Maven Central, Bintray, JCenter,JFrog, etc.).

**Comment by cescoffier** [comment]
Hi, 

I just published the artifacts in https://oss.sonatype.org/content/repositories/snapshots/me/escoffier/vertx/

So, you just need to add the https://oss.sonatype.org/content/repositories/snapshots (snapshot) repository to your project.

**Comment by cazacugmihai** [comment]
Thank you!
